name: p_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=>3.7
  - numpy=>1.19
  - scipy>=1.6
  - pillow>=8.2
  - matplotlib>=3.3
  - astropy>=4.2
  - pytest>=6.2
  - sphinx>=3.4
  - jupyter>=1.0
  - ipykernel
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - pip
  - setuptools