channels:
  - conda-forge
dependencies:
  - python>=3
  - pandoc
  - ipykernel
  - pip
  - pip:
    - nbsphinx
    - numpydoc
    - numpy
    - scipy
    - astropy
    - astroquery
  - setuptools:
    - .